---
title: Analysis of Compressive Strength
author: Sheral 20BCE1182, Anjali 20BCE1320, Arunima 20BCE1808
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#loading packages
library(forecast) #building model and predicting
library(Metrics)  #calculating errors
```

```{r}
# reading data
data = read.csv("datasettime.csv")
```

```{r}
# splitting data into train and valid sets
train = data[1:5,]
valid = data[6:nrow(data),]
```

```{r}
# removing "Time" column
train$time = NULL
# training model
model = auto.arima(train)
# model summary
summary(model)
```

```{r}
# forecasting
forecast = predict(model,711)
forecast
```

```{r}
# plotting predictions for validation set
plot(unlist(train), type='o', label='Train')
plot(unlist(valid), type='o', label='Valid')
plot(unlist(forecast), type='o', label='Prediction')
```

```{r}
# evaluation
rmse1 = rmse(valid$str_mpa, forecast$pred)
rmse1  #root mean square error
mse1 = rmse1^2
mse1  #mean square error
```

```{r}
######
data1=as.data.frame(data)  #converting dataset into dataframe
stren = data1$str_mpa
time1 = data1$time
autoplot(ts(stren))  #time(hrs) vs compressive strength
model1=auto.arima(stren)  #model building
model1
pred1=forecast(model1,h=1)  #predicted compressive strength
pred1
```

